name: Deploy to Alibaba Cloud ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: |
        npx prisma generate
        npm run build
        
    - name: Deploy to Alibaba Cloud ECS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.ALIYUN_HOST }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        key: ${{ secrets.ALIYUN_SSH_KEY }}
        port: ${{ secrets.ALIYUN_PORT }}
        script: |
          cd /opt/huitong-material
          
          # 拉取最新代码
          git pull origin main
          
          # 停止现有服务
          docker-compose down
          
          # 重新构建并启动服务
          docker-compose build --no-cache
          docker-compose up -d
          
          # 等待服务启动
          sleep 30
          
          # 运行数据库迁移
          docker-compose exec -T app npx prisma db push
          
          # 检查服务状态
          docker-compose ps